<Monitor<TimeLimit<CartPoleEnv<CartPole-v1>>>>
EnvSpec(CartPole-v1)
Box([-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38], [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38], (4,), float32)
Discrete(2)
example transition
OrderedDict([('obs', array([ 1.6774637e+00, -3.2515270e+38, -3.6088797e-01,  3.2982719e+38],
      dtype=float32)), ('action', 0), ('reward', 0.0), ('done', False)])
buffer spec
[('obs', '<f4', (4,)), ('action', '<i8'), ('reward', '<f8'), ('done', 'u1'), ('value', '<f4'), ('log_prob', '<f4')]
Agent(
  (actor): Sequential(
    (0): Linear(in_features=4, out_features=256, bias=True)
    (1): Tanh()
    (2): Linear(in_features=256, out_features=256, bias=True)
    (3): Tanh()
    (4): Linear(in_features=256, out_features=2, bias=True)
    (5): Softmax(dim=-1)
  )
  (critic): Sequential(
    (0): Linear(in_features=4, out_features=256, bias=True)
    (1): Tanh()
    (2): Linear(in_features=256, out_features=256, bias=True)
    (3): Tanh()
    (4): Linear(in_features=256, out_features=1, bias=True)
  )
)
/home/anthony/PycharmProjects/ppo_kata/model.py:34: RuntimeWarning: invalid value encountered in double_scalars
  advs[i] = delta + masks[i] * (gam * lamb * advs[i + 1])
Traceback (most recent call last):
  File "/home/anthony/PycharmProjects/ppo_kata/main.py", line 127, in <module>
    loss_dict = agent.learn()
  File "/home/anthony/PycharmProjects/ppo_kata/model.py", line 155, in learn
    ac_dist, values = self(batch['obs'])
  File "/home/anthony/.pyenv/versions/dev/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/anthony/PycharmProjects/ppo_kata/model.py", line 93, in forward
    ac_dist = self._policy(x)
  File "/home/anthony/PycharmProjects/ppo_kata/model.py", line 120, in _policy
    return Categorical(probs.cpu())
  File "/home/anthony/.pyenv/versions/dev/lib/python3.7/site-packages/torch/distributions/categorical.py", line 64, in __init__
    super(Categorical, self).__init__(batch_shape, validate_args=validate_args)
  File "/home/anthony/.pyenv/versions/dev/lib/python3.7/site-packages/torch/distributions/distribution.py", line 53, in __init__
    raise ValueError("The parameter {} has invalid values".format(param))
ValueError: The parameter probs has invalid values